micronaut:
  application:
    name: authentication
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        cognito:
          client-id: '${OAUTH_CLIENT_ID}'
          openid:
            issuer: 'https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_POOL_ID}/'
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
    endpoints:
      logout:
        enabled: true
        get-allowed: true
